package com.task.common.bean;

// Generated 2014-6-3 9:50:12 by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

import com.task.common.utils.FieldMeta;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {
	
	private Integer userId;
	private String userName;
	private String realName;
	private String deptName;
	private String password;
	private int flag;
	private String headUrl;
	private Integer qq;
	private String email;
	private Timestamp createTime;
	private Timestamp lastLoginTime;
	private String phoneNum;
	
	@FieldMeta(isField=false)
	private int deptId; 
	@FieldMeta(isField=false)
	private Department department;

	public User() {
	}

	public User(String userName, String password) {
		this.userName = userName;
		this.password = password;
	}

	public User(Department department, String userName, String realName, String password, Byte flag, String headUrl, Integer qq, String email, Timestamp createTime, Timestamp lastLoginTime) {
		this.department = department;
		this.userName = userName;
		this.realName = realName;
		this.password = password;
		this.flag = flag;
		this.headUrl = headUrl;
		this.qq = qq;
		this.email = email;
		this.createTime = createTime;
		this.lastLoginTime = lastLoginTime;
	}

	

	public Department getDepartment() {
		return this.department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getRealName() {
		return this.realName;
	}

	public void setRealName(String realName) {
		this.realName = realName;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	
	public Integer getQq() {
		return this.qq;
	}

	public void setQq(Integer qq) {
		this.qq = qq;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Timestamp getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Timestamp createTime) {
		this.createTime = createTime;
	}

	public Timestamp getLastLoginTime() {
		return this.lastLoginTime;
	}

	public void setLastLoginTime(Timestamp lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	public Integer getUserId() {
		return userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getDeptName() {
		return deptName;
	}

	public void setDeptName(String deptName) {
		this.deptName = deptName;
	}

	public String getPhoneNum() {
		return phoneNum;
	}

	public void setPhoneNum(String phoneNum) {
		this.phoneNum = phoneNum;
	}
	
	public int getFlag() {
		return flag;
	}

	public void setFlag(int i) {
		this.flag = i;
	}

	public String getHeadUrl() {
		return headUrl;
	}

	public void setHeadUrl(String headUrl) {
		this.headUrl = headUrl;
	}

	public int getDeptId() {
		return deptId;
	}

	public void setDeptId(int deptId) {
		this.deptId = deptId;
	}



}
